In [1]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

engine = create_engine(f'postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/f1pace')

In [3]:
from fastf1 import get_event_schedule
import pandas as pd

events_schedule_df = pd.DataFrame()
for year in range(2018, 2027):

    response_frame = get_event_schedule(year)
    response_frame['year'] = year

    events_schedule_df = pd.concat([events_schedule_df, response_frame])
    
events_schedule_df

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport,year
0,1,Australia,Melbourne,FORMULA 1 2018 ROLEX AUSTRALIAN GRAND PRIX,2018-03-25,Australian Grand Prix,conventional,Practice 1,2018-03-23 12:00:00+11:00,2018-03-23 01:00:00,...,2018-03-24 14:00:00+11:00,2018-03-24 03:00:00,Qualifying,2018-03-24 17:00:00+11:00,2018-03-24 06:00:00,Race,2018-03-25 16:10:00+11:00,2018-03-25 05:10:00,True,2018
1,2,Bahrain,Sakhir,FORMULA 1 2018 GULF AIR BAHRAIN GRAND PRIX,2018-04-08,Bahrain Grand Prix,conventional,Practice 1,2018-04-06 14:00:00+03:00,2018-04-06 11:00:00,...,2018-04-07 15:00:00+03:00,2018-04-07 12:00:00,Qualifying,2018-04-07 18:00:00+03:00,2018-04-07 15:00:00,Race,2018-04-08 18:10:00+03:00,2018-04-08 15:10:00,True,2018
2,3,China,Shanghai,FORMULA 1 2018 HEINEKEN CHINESE GRAND PRIX,2018-04-15,Chinese Grand Prix,conventional,Practice 1,2018-04-13 10:00:00+08:00,2018-04-13 02:00:00,...,2018-04-14 11:00:00+08:00,2018-04-14 03:00:00,Qualifying,2018-04-14 14:00:00+08:00,2018-04-14 06:00:00,Race,2018-04-15 14:10:00+08:00,2018-04-15 06:10:00,True,2018
3,4,Azerbaijan,Baku,FORMULA 1 2018 AZERBAIJAN GRAND PRIX,2018-04-29,Azerbaijan Grand Prix,conventional,Practice 1,2018-04-27 13:00:00+04:00,2018-04-27 09:00:00,...,2018-04-28 14:00:00+04:00,2018-04-28 10:00:00,Qualifying,2018-04-28 17:00:00+04:00,2018-04-28 13:00:00,Race,2018-04-29 16:10:00+04:00,2018-04-29 12:10:00,True,2018
4,5,Spain,Barcelona,FORMULA 1 GRAN PREMIO DE ESPAÑA EMIRATES 2018,2018-05-13,Spanish Grand Prix,conventional,Practice 1,2018-05-11 11:00:00+02:00,2018-05-11 09:00:00,...,2018-05-12 12:00:00+02:00,2018-05-12 10:00:00,Qualifying,2018-05-12 15:00:00+02:00,2018-05-12 13:00:00,Race,2018-05-13 15:10:00+02:00,2018-05-13 13:10:00,True,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,18,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026,2026-11-01,Mexico City Grand Prix,conventional,Practice 1,2026-10-30 12:30:00-06:00,2026-10-30 18:30:00,...,2026-10-31 11:30:00-06:00,2026-10-31 17:30:00,Qualifying,2026-10-31 15:00:00-06:00,2026-10-31 21:00:00,Race,2026-11-01 14:00:00-06:00,2026-11-01 20:00:00,True,2026
20,19,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2026-11-08,São Paulo Grand Prix,conventional,Practice 1,2026-11-06 12:30:00-03:00,2026-11-06 15:30:00,...,2026-11-07 11:30:00-03:00,2026-11-07 14:30:00,Qualifying,2026-11-07 15:00:00-03:00,2026-11-07 18:00:00,Race,2026-11-08 14:00:00-03:00,2026-11-08 17:00:00,True,2026
21,20,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026,2026-11-21,Las Vegas Grand Prix,conventional,Practice 1,2026-11-19 16:30:00-08:00,2026-11-20 00:30:00,...,2026-11-20 16:30:00-08:00,2026-11-21 00:30:00,Qualifying,2026-11-20 20:00:00-08:00,2026-11-21 04:00:00,Race,2026-11-21 20:00:00-08:00,2026-11-22 04:00:00,True,2026
22,21,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026,2026-11-29,Qatar Grand Prix,conventional,Practice 1,2026-11-27 16:30:00+03:00,2026-11-27 13:30:00,...,2026-11-28 17:30:00+03:00,2026-11-28 14:30:00,Qualifying,2026-11-28 21:00:00+03:00,2026-11-28 18:00:00,Race,2026-11-29 19:00:00+03:00,2026-11-29 16:00:00,True,2026
23,22,United Arab Emirates,Yas Marina,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2026-12-06,Abu Dhabi Grand Prix,conventional,Practice 1,2026-12-04 13:30:00+04:00,2026-12-04 09:30:00,...,2026-12-05 14:30:00+04:00,2026-12-05 10:30:00,Qualifying,2026-12-05 18:00:00+04:00,2026-12-05 14:00:00,Race,2026-12-06 17:00:00+04:00,2026-12-06 13:00:00,True,2026

# Events

In [60]:
events_df = (
    events_schedule_df[["year", "RoundNumber", "EventFormat", "Country", "Location"]]
    .reset_index(drop=True)
)
events_df["EventFormat"] = events_df["EventFormat"].apply(lambda x : False if x=="conventional" else True)
events_df

     year  RoundNumber  EventFormat               Country     Location
0    2018            1        False             Australia    Melbourne
1    2018            2        False               Bahrain       Sakhir
2    2018            3        False                 China     Shanghai
3    2018            4        False            Azerbaijan         Baku
4    2018            5        False                 Spain    Barcelona
..    ...          ...          ...                   ...          ...
200  2026           18        False                Mexico  Mexico City
201  2026           19        False                Brazil    São Paulo
202  2026           20        False         United States    Las Vegas
203  2026           21        False                 Qatar       Lusail
204  2026           22        False  United Arab Emirates   Yas Marina

[205 rows x 5 columns]

In [ ]:
circuits_df = pd.read_sql('SELECT id, country, location, circuit_name FROM tracks', engine)
circuits_df.head()

   id     country   location                    circuit_name
0   0   Australia  Melbourne  Albert Park Grand Prix Circuit
1   1         USA     Austin         Circuit of the Americas
2   2     Bahrain     Sakhir   Bahrain International Circuit
3   3  Azerbaijan       Baku               Baku City Circuit
4   4       Spain  Barcelona  Circuit de Barcelona-Catalunya

In [44]:
circuits_df["circuit_info"] = (circuits_df["country"] + " " + circuits_df["location"] + " " + circuits_df["circuit_name"]).str.lower()
circuits_df[["id", "circuit_info"]].head()

   id                                       circuit_info
0   0  australia melbourne albert park grand prix cir...
1   1                 usa austin circuit of the americas
2   2       bahrain sakhir bahrain international circuit
3   3                  azerbaijan baku baku city circuit
4   4     spain barcelona circuit de barcelona-catalunya

In [109]:
def to_circuit_id(row):

    location = row["Location"].lower()

    replace_dict = {
        "Montréal" : "Montreal", 
        "Yas Island" : "Yas", 
        "Miami Gardens" : "Miami",
    }
    for key in replace_dict:
        location = location.replace(key.lower(), replace_dict[key].lower())

    for i in range(len(circuits_df)):
        if location in circuits_df.loc[i, "circuit_info"]:
            return int(circuits_df.loc[i, "id"])
    return None

events_df["circuit_id"] = events_df.apply(to_circuit_id, axis=1)
events_df['circuit_id'] = events_df['circuit_id'].astype('Int32')
events_df

     year  RoundNumber  ...     Location circuit_id
0    2018            1  ...    Melbourne          0
1    2018            2  ...       Sakhir          2
2    2018            3  ...     Shanghai         14
3    2018            4  ...         Baku          3
4    2018            5  ...    Barcelona          4
..    ...          ...  ...          ...        ...
200  2026           18  ...  Mexico City         13
201  2026           19  ...    São Paulo          7
202  2026           20  ...    Las Vegas         30
203  2026           21  ...       Lusail         27
204  2026           22  ...   Yas Marina         20

[205 rows x 6 columns]

In [110]:
events_df[pd.isna(events_df["circuit_id"])]

Empty DataFrame
Columns: [year, RoundNumber, EventFormat, Country, Location, circuit_id]
Index: []

In [152]:

events_df_clean = (
    events_df[events_df["RoundNumber"]>0][["circuit_id", "year", "RoundNumber", "EventFormat"]]
    .rename(columns={
        "RoundNumber" : "round",
        "EventFormat" : "is_sprint"
    })
)

events_df_clean

     circuit_id  year  round  is_sprint
0             0  2018      1      False
1             2  2018      2      False
2            14  2018      3      False
3             3  2018      4      False
4             4  2018      5      False
..          ...   ...    ...        ...
200          13  2026     18      False
201           7  2026     19      False
202          30  2026     20      False
203          27  2026     21      False
204          20  2026     22      False

[195 rows x 4 columns]

In [154]:
events_df_clean.iloc[43]

circuit_id       11
year           2020
round             2
is_sprint     False
Name: 45, dtype: object

In [195]:
with engine.connect() as conn:
    conn.execute(text("DELETE FROM events"))
    conn.commit()

In [196]:
events_df_clean.to_sql("events", engine, if_exists="append", index=True, index_label="id")

195

# Sessions

In [197]:
session_names = ["Unknown",
                 "Practice 1", 
                 "Practice 2", 
                 "Practice 3", 
                 "Qualifying", 
                 "Race", 
                 "Sprint Qualifying", 
                 "Sprint"]

session_types_df = pd.DataFrame(session_names, columns=["name"])
session_types_df

                name
0            Unknown
1         Practice 1
2         Practice 2
3         Practice 3
4         Qualifying
5               Race
6  Sprint Qualifying
7             Sprint

In [199]:
session_types_df.to_sql("session_types", engine, if_exists='append', index=True, index_label="id")

8

In [200]:
session_data = []
for i in range(len(events_schedule_df)):
    event = events_schedule_df.iloc[i]

    if event["EventFormat"] == 'testing':
        continue

    event_id = events_df_clean[(events_df_clean["year"] == event["year"]) &
                               (events_df_clean["round"] == event["RoundNumber"])].index
     
    if len(event_id) != 1:
        print(event_id)
        raise ValueError
    event_id = event_id[0]

    for session_num in range(1, 6):
        s_type = event[f"Session{session_num}"]
        if s_type in session_names:
            s_type_ind = session_names.index(s_type)
        else:
            s_type_ind = session_names.index("Unknown")
        s_datetime = event[f"Session{session_num}DateUtc"]

        session_data.append((event_id, s_type_ind, s_datetime))

In [201]:
sessions_df = pd.DataFrame(data=session_data, 
                        columns=["event_id", "session_type", "datetime_start_utc"])

sessions_df

     event_id  session_type  datetime_start_utc
0           0             1 2018-03-23 01:00:00
1           0             2 2018-03-23 05:00:00
2           0             3 2018-03-24 03:00:00
3           0             4 2018-03-24 06:00:00
4           0             5 2018-03-25 05:10:00
..        ...           ...                 ...
970       204             1 2026-12-04 09:30:00
971       204             2 2026-12-04 13:00:00
972       204             3 2026-12-05 10:30:00
973       204             4 2026-12-05 14:00:00
974       204             5 2026-12-06 13:00:00

[975 rows x 3 columns]

In [202]:
sessions_df.to_sql("sessions", engine, if_exists='append', index=True, index_label="id")

975