In [1]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

engine = create_engine(f'postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/f1pace')

In [2]:
import pandas as pd

In [3]:
tyres = [
    'UNKNOWN',
    'SOFT', 
    'MEDIUM', 
    'HARD', 
    'INTERMEDIATE',
    'WET',
]

track_statuses = {
    1 : 'Track clear',
    2 : 'Yellow flag',
    3 : 'Unknown',
    4 : 'Safity Car',
    5 : 'Red flag',
    6 : 'Virtual Safity Car',
    7 : 'Virtual Safity Car ending',
}

In [4]:
tyres_df = pd.DataFrame(tyres, columns=['name'])
tyres_df

           name
0       UNKNOWN
1          SOFT
2        MEDIUM
3          HARD
4  INTERMEDIATE
5           WET

In [5]:
track_statuses_df = pd.DataFrame.from_dict(track_statuses, orient="index", columns=["name"])
track_statuses_df

                        name
1                Track clear
2                Yellow flag
3                    Unknown
4                 Safity Car
5                   Red flag
6         Virtual Safity Car
7  Virtual Safity Car ending

In [42]:
tyres_df.to_sql("tyres", engine, index=True, index_label='id', if_exists='append')
track_statuses_df.to_sql("track_statuses", engine, index=True, index_label='id', if_exists='append')

7

In [ ]:
from fastf1 import get_session, set_log_level
import fastf1

# fastf1.Cache.clear_cache()
set_log_level("WARNING")

In [7]:
with engine.connect() as conn:
    cursor = conn.execute(text("select s.id, e.year, e.round, st.name from sessions s join events e on s.event_id = e.id join session_types st on s.session_type = st.id where s.session_type in (5, 7) and e.year > 2020"))
    sessions = cursor.fetchall()
 
sessions

[(299, 2021, 1, 'Race'),
 (304, 2021, 2, 'Race'),
 (309, 2021, 3, 'Race'),
 (314, 2021, 4, 'Race'),
 (319, 2021, 5, 'Race'),
 (324, 2021, 6, 'Race'),
 (329, 2021, 7, 'Race'),
 (334, 2021, 8, 'Race'),
 (339, 2021, 9, 'Race'),
 (343, 2021, 10, 'Sprint'),
 (344, 2021, 10, 'Race'),
 (349, 2021, 11, 'Race'),
 (354, 2021, 12, 'Race'),
 (359, 2021, 13, 'Race'),
 (363, 2021, 14, 'Sprint'),
 (364, 2021, 14, 'Race'),
 (369, 2021, 15, 'Race'),
 (374, 2021, 16, 'Race'),
 (379, 2021, 17, 'Race'),
 (384, 2021, 18, 'Race'),
 (388, 2021, 19, 'Sprint'),
 (389, 2021, 19, 'Race'),
 (394, 2021, 20, 'Race'),
 (399, 2021, 21, 'Race'),
 (404, 2021, 22, 'Race'),
 (409, 2022, 1, 'Race'),
 (414, 2022, 2, 'Race'),
 (419, 2022, 3, 'Race'),
 (423, 2022, 4, 'Sprint'),
 (424, 2022, 4, 'Race'),
 (429, 2022, 5, 'Race'),
 (434, 2022, 6, 'Race'),
 (439, 2022, 7, 'Race'),
 (444, 2022, 8, 'Race'),
 (449, 2022, 9, 'Race'),
 (454, 2022, 10, 'Race'),
 (458, 2022, 11, 'Sprint'),
 (459, 2022, 11, 'Race'),
 (464, 2022, 12, 'Race'),
 (469, 2022, 13, 'Race'),
 (474, 2022, 14, 'Race'),
 (479, 2022, 15, 'Race'),
 (484, 2022, 16, 'Race'),
 (489, 2022, 17, 'Race'),
 (494, 2022, 18, 'Race'),
 (499, 2022, 19, 'Race'),
 (504, 2022, 20, 'Race'),
 (508, 2022, 21, 'Sprint'),
 (509, 2022, 21, 'Race'),
 (514, 2022, 22, 'Race'),
 (519, 2023, 1, 'Race'),
 (524, 2023, 2, 'Race'),
 (529, 2023, 3, 'Race'),
 (533, 2023, 4, 'Sprint'),
 (534, 2023, 4, 'Race'),
 (539, 2023, 5, 'Race'),
 (544, 2023, 6, 'Race'),
 (549, 2023, 7, 'Race'),
 (554, 2023, 8, 'Race'),
 (558, 2023, 9, 'Sprint'),
 (559, 2023, 9, 'Race'),
 (564, 2023, 10, 'Race'),
 (569, 2023, 11, 'Race'),
 (573, 2023, 12, 'Sprint'),
 (574, 2023, 12, 'Race'),
 (579, 2023, 13, 'Race'),
 (584, 2023, 14, 'Race'),
 (589, 2023, 15, 'Race'),
 (594, 2023, 16, 'Race'),
 (598, 2023, 17, 'Sprint'),
 (599, 2023, 17, 'Race'),
 (603, 2023, 18, 'Sprint'),
 (604, 2023, 18, 'Race'),
 (609, 2023, 19, 'Race'),
 (613, 2023, 20, 'Sprint'),
 (614, 2023, 20, 'Race'),
 (619, 2023, 21, 'Race'),
 (624, 2023, 22, 'Race'),
 (629, 2024, 1, 'Race'),
 (634, 2024, 2, 'Race'),
 (639, 2024, 3, 'Race'),
 (644, 2024, 4, 'Race'),
 (647, 2024, 5, 'Sprint'),
 (649, 2024, 5, 'Race'),
 (652, 2024, 6, 'Sprint'),
 (654, 2024, 6, 'Race'),
 (659, 2024, 7, 'Race'),
 (664, 2024, 8, 'Race'),
 (669, 2024, 9, 'Race'),
 (674, 2024, 10, 'Race'),
 (677, 2024, 11, 'Sprint'),
 (679, 2024, 11, 'Race'),
 (684, 2024, 12, 'Race'),
 (689, 2024, 13, 'Race'),
 (694, 2024, 14, 'Race'),
 (699, 2024, 15, 'Race'),
 (704, 2024, 16, 'Race'),
 (709, 2024, 17, 'Race'),
 (714, 2024, 18, 'Race'),
 (717, 2024, 19, 'Sprint'),
 (719, 2024, 19, 'Race'),
 (724, 2024, 20, 'Race'),
 (727, 2024, 21, 'Sprint'),
 (729, 2024, 21, 'Race'),
 (734, 2024, 22, 'Race'),
 (737, 2024, 23, 'Sprint'),
 (739, 2024, 23, 'Race'),
 (744, 2024, 24, 'Race'),
 (749, 2025, 1, 'Race'),
 (752, 2025, 2, 'Sprint'),
 (754, 2025, 2, 'Race'),
 (759, 2025, 3, 'Race'),
 (764, 2025, 4, 'Race'),
 (769, 2025, 5, 'Race'),
 (772, 2025, 6, 'Sprint'),
 (774, 2025, 6, 'Race'),
 (779, 2025, 7, 'Race'),
 (784, 2025, 8, 'Race'),
 (789, 2025, 9, 'Race'),
 (794, 2025, 10, 'Race'),
 (799, 2025, 11, 'Race'),
 (804, 2025, 12, 'Race'),
 (807, 2025, 13, 'Sprint'),
 (809, 2025, 13, 'Race'),
 (814, 2025, 14, 'Race'),
 (819, 2025, 15, 'Race'),
 (824, 2025, 16, 'Race'),
 (829, 2025, 17, 'Race'),
 (834, 2025, 18, 'Race'),
 (837, 2025, 19, 'Sprint'),
 (839, 2025, 19, 'Race'),
 (844, 2025, 20, 'Race'),
 (847, 2025, 21, 'Sprint'),
 (849, 2025, 21, 'Race'),
 (854, 2025, 22, 'Race'),
 (857, 2025, 23, 'Sprint'),
 (859, 2025, 23, 'Race'),
 (864, 2025, 24, 'Race'),
 (869, 2026, 1, 'Race'),
 (872, 2026, 2, 'Sprint'),
 (874, 2026, 2, 'Race'),
 (879, 2026, 3, 'Race'),
 (882, 2026, 4, 'Sprint'),
 (884, 2026, 4, 'Race'),
 (887, 2026, 5, 'Sprint'),
 (889, 2026, 5, 'Race'),
 (894, 2026, 6, 'Race'),
 (899, 2026, 7, 'Race'),
 (904, 2026, 8, 'Race'),
 (907, 2026, 9, 'Sprint'),
 (909, 2026, 9, 'Race'),
 (914, 2026, 10, 'Race'),
 (919, 2026, 11, 'Race'),
 (922, 2026, 12, 'Sprint'),
 (924, 2026, 12, 'Race'),
 (929, 2026, 13, 'Race'),
 (934, 2026, 14, 'Race'),
 (939, 2026, 15, 'Race'),
 (942, 2026, 16, 'Sprint'),
 (944, 2026, 16, 'Race'),
 (949, 2026, 17, 'Race'),
 (954, 2026, 18, 'Race'),
 (959, 2026, 19, 'Race'),
 (964, 2026, 20, 'Race'),
 (969, 2026, 21, 'Race'),
 (974, 2026, 22, 'Race')]

In [10]:
def convert_lap_time(x):
    return x.seconds +  x.microseconds * 1e-6

def convert_tyre(x):
    if not x in tyres:
        return tyres.index("UNKNOWN")
    return tyres.index(x)

def convert_track_status(x):
    priority = [5, 4, 6, 7, 2, 1, 3]
    for p in priority:
        if str(p) in x:
            return p
    return 3

def find_weather(row, weather):
    time1 = row["Time"]
    for i in range(len(weather)):   
        time2 = weather.loc[i, "Time"] 
        if time2 > time1:
            break
    return weather.loc[i][["AirTemp", "TrackTemp", "Humidity", "Rainfall", "WindDirection", "WindSpeed"]]



def parce_laps(s_id, year, round, s_type):
    
    session_id = s_id
    session = get_session(year, round, s_type)
    session.load(telemetry=False, laps=True, weather=True)

    laps_df = session.laps[["Time", "Driver", "DriverNumber", 
                            "LapTime", "Sector1Time", "Sector2Time", "Sector3Time",
                            "LapNumber", "Stint", "TyreLife", "Compound", "Deleted", "TrackStatus", "Position"]].copy()


    laps_df["LapTime"] = laps_df["LapTime"].apply(convert_lap_time)
    laps_df["Sector1Time"] = laps_df["Sector1Time"].apply(convert_lap_time)
    laps_df["Sector2Time"] = laps_df["Sector2Time"].apply(convert_lap_time)
    laps_df["Sector3Time"] = laps_df["Sector3Time"].apply(convert_lap_time)
    laps_df["Compound"] = laps_df["Compound"].apply(convert_tyre)
    laps_df["TrackStatus"] = laps_df["TrackStatus"].apply(convert_track_status)
    laps_df["session_id"] = session_id

    laps_df["LapNumber"] = laps_df["LapNumber"].astype('Int64')
    laps_df["TyreLife"] = laps_df["TyreLife"].astype('Int64')
    laps_df["Stint"] = laps_df["Stint"].astype('Int64')
    laps_df["DriverNumber"] = laps_df["DriverNumber"].astype('Int64')
    laps_df["Position"] = laps_df["Position"].astype('Int64')

    laps_df[["AirTemp", "TrackTemp", "Humidity", 
            "Rainfall", "WindDirection", 
            "WindSpeed"]] = laps_df.apply(find_weather, axis=1, args=(session.weather_data,))

    laps_df = (
        laps_df
        .rename(columns={
            "Driver"       : "driver_abbr",
            "DriverNumber" : "driver_num",
            "LapTime"      : "lap_time",
            "Sector1Time"  : "lap_s1_time",
            "Sector2Time"  : "lap_s2_time",
            "Sector3Time"  : "lap_s3_time",
            "LapNumber"    : "lap_number",
            "Stint"        : "stint_number",
            "TyreLife"     : "tyre_age",
            "Compound"     : "tyre_type",
            "Deleted"      : "is_deleted",
            "TrackStatus"  : "track_status",
            "AirTemp"      : "air_temp", 
            "TrackTemp"    : "track_temp", 
            "Humidity"     : "humidity",
            "Rainfall"     : "is_rain",
            "WindDirection": "wind_direction",
            "WindSpeed"    : "wind_speed",
            "Position"     : "position",
        })
        .drop("Time", axis=1)
    )

    laps_df.to_sql('laps', engine, index=False, if_exists='append')

In [14]:
from tqdm import tqdm
import time

for s in tqdm(sessions):
    with engine.connect() as conn:
        cursor = conn.execute(text(f"SELECT * FROM laps WHERE session_id = {s[0]}"))
        curr_s = cursor.fetchall()
    if len(curr_s)!=0:
        print(f"Уже есть запись {s}")
        continue

    try:
        parce_laps(s[0], s[1], s[2], s[3])
        time.sleep(5)

    except Exception as e:
        print(e)
        print(s)

  0%|          | 0/166 [00:00<?, ?it/s]

  8%|▊         | 14/166 [00:00<00:02, 71.74it/s]

Уже есть запись (299, 2021, 1, 'Race')
Уже есть запись (304, 2021, 2, 'Race')
Уже есть запись (309, 2021, 3, 'Race')
Уже есть запись (314, 2021, 4, 'Race')
Уже есть запись (319, 2021, 5, 'Race')
Уже есть запись (324, 2021, 6, 'Race')
Уже есть запись (329, 2021, 7, 'Race')
Уже есть запись (334, 2021, 8, 'Race')
Уже есть запись (339, 2021, 9, 'Race')
Уже есть запись (343, 2021, 10, 'Sprint')
Уже есть запись (344, 2021, 10, 'Race')
Уже есть запись (349, 2021, 11, 'Race')
Уже есть запись (354, 2021, 12, 'Race')
Уже есть запись (359, 2021, 13, 'Race')
Уже есть запись (363, 2021, 14, 'Sprint')
Уже есть запись (364, 2021, 14, 'Race')
Уже есть запись (369, 2021, 15, 'Race')
Уже есть запись (374, 2021, 16, 'Race')
Уже есть запись (379, 2021, 17, 'Race')

 20%|██        | 34/166 [00:00<00:01, 89.22it/s]

Уже есть запись (384, 2021, 18, 'Race')
Уже есть запись (388, 2021, 19, 'Sprint')
Уже есть запись (389, 2021, 19, 'Race')
Уже есть запись (394, 2021, 20, 'Race')
Уже есть запись (399, 2021, 21, 'Race')
Уже есть запись (404, 2021, 22, 'Race')
Уже есть запись (409, 2022, 1, 'Race')
Уже есть запись (414, 2022, 2, 'Race')
Уже есть запись (419, 2022, 3, 'Race')
Уже есть запись (423, 2022, 4, 'Sprint')
Уже есть запись (424, 2022, 4, 'Race')
Уже есть запись (429, 2022, 5, 'Race')
Уже есть запись (434, 2022, 6, 'Race')
Уже есть запись (439, 2022, 7, 'Race')
Уже есть запись (444, 2022, 8, 'Race')
Уже есть запись (449, 2022, 9, 'Race')
Уже есть запись (454, 2022, 10, 'Race')
Уже есть запись (458, 2022, 11, 'Sprint')
Уже есть запись (459, 2022, 11, 'Race')
Уже есть запись (464, 2022, 12, 'Race')

 33%|███▎      | 55/166 [00:00<00:01, 97.08it/s]

Уже есть запись (469, 2022, 13, 'Race')
Уже есть запись (474, 2022, 14, 'Race')
Уже есть запись (479, 2022, 15, 'Race')
Уже есть запись (484, 2022, 16, 'Race')
Уже есть запись (489, 2022, 17, 'Race')
Уже есть запись (494, 2022, 18, 'Race')
Уже есть запись (499, 2022, 19, 'Race')
Уже есть запись (504, 2022, 20, 'Race')
Уже есть запись (508, 2022, 21, 'Sprint')
Уже есть запись (509, 2022, 21, 'Race')
Уже есть запись (514, 2022, 22, 'Race')
Уже есть запись (519, 2023, 1, 'Race')
Уже есть запись (524, 2023, 2, 'Race')
Уже есть запись (529, 2023, 3, 'Race')
Уже есть запись (533, 2023, 4, 'Sprint')
Уже есть запись (534, 2023, 4, 'Race')
Уже есть запись (539, 2023, 5, 'Race')
Уже есть запись (544, 2023, 6, 'Race')
Уже есть запись (549, 2023, 7, 'Race')
Уже есть запись (554, 2023, 8, 'Race')
Уже есть запись (558, 2023, 9, 'Sprint')

 46%|████▌     | 76/166 [00:00<00:00, 99.75it/s]

Уже есть запись (559, 2023, 9, 'Race')
Уже есть запись (564, 2023, 10, 'Race')
Уже есть запись (569, 2023, 11, 'Race')
Уже есть запись (573, 2023, 12, 'Sprint')
Уже есть запись (574, 2023, 12, 'Race')
Уже есть запись (579, 2023, 13, 'Race')
Уже есть запись (584, 2023, 14, 'Race')
Уже есть запись (589, 2023, 15, 'Race')
Уже есть запись (594, 2023, 16, 'Race')
Уже есть запись (598, 2023, 17, 'Sprint')
Уже есть запись (599, 2023, 17, 'Race')
Уже есть запись (603, 2023, 18, 'Sprint')
Уже есть запись (604, 2023, 18, 'Race')
Уже есть запись (609, 2023, 19, 'Race')
Уже есть запись (613, 2023, 20, 'Sprint')
Уже есть запись (614, 2023, 20, 'Race')
Уже есть запись (619, 2023, 21, 'Race')
Уже есть запись (624, 2023, 22, 'Race')
Уже есть запись (629, 2024, 1, 'Race')
Уже есть запись (634, 2024, 2, 'Race')
Уже есть запись (639, 2024, 3, 'Race')

 58%|█████▊    | 96/166 [00:01<00:00, 93.63it/s]

Уже есть запись (644, 2024, 4, 'Race')
Уже есть запись (647, 2024, 5, 'Sprint')
Уже есть запись (649, 2024, 5, 'Race')
Уже есть запись (652, 2024, 6, 'Sprint')
Уже есть запись (654, 2024, 6, 'Race')
Уже есть запись (659, 2024, 7, 'Race')
Уже есть запись (664, 2024, 8, 'Race')
Уже есть запись (669, 2024, 9, 'Race')
Уже есть запись (674, 2024, 10, 'Race')
Уже есть запись (677, 2024, 11, 'Sprint')
Уже есть запись (679, 2024, 11, 'Race')
Уже есть запись (684, 2024, 12, 'Race')
Уже есть запись (689, 2024, 13, 'Race')
Уже есть запись (694, 2024, 14, 'Race')
Уже есть запись (699, 2024, 15, 'Race')
Уже есть запись (704, 2024, 16, 'Race')
Уже есть запись (709, 2024, 17, 'Race')
Уже есть запись (714, 2024, 18, 'Race')
Уже есть запись (717, 2024, 19, 'Sprint')

 64%|██████▍   | 107/166 [00:01<00:00, 97.78it/s]

Уже есть запись (719, 2024, 19, 'Race')
Уже есть запись (724, 2024, 20, 'Race')
Уже есть запись (727, 2024, 21, 'Sprint')
Уже есть запись (729, 2024, 21, 'Race')
Уже есть запись (734, 2024, 22, 'Race')
Уже есть запись (737, 2024, 23, 'Sprint')
Уже есть запись (739, 2024, 23, 'Race')
Уже есть запись (744, 2024, 24, 'Race')
Уже есть запись (749, 2025, 1, 'Race')
Уже есть запись (752, 2025, 2, 'Sprint')
Уже есть запись (754, 2025, 2, 'Race')
Уже есть запись (759, 2025, 3, 'Race')
Уже есть запись (764, 2025, 4, 'Race')
Уже есть запись (769, 2025, 5, 'Race')
Уже есть запись (772, 2025, 6, 'Sprint')
Уже есть запись (774, 2025, 6, 'Race')
Уже есть запись (779, 2025, 7, 'Race')

 73%|███████▎  | 122/166 [01:11<02:32,  3.45s/it]_api        WARNING 	Failed to align laps for drivers: ['10']
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
 74%|███████▍  | 123/166 [01:26<03:29,  4.87s/it]core        WARNING 	Fixed incorrect tyre stint information for driver '81'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
 77%|███████▋  | 127/166 [02:25<06:47, 10.46s/it]core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
 78%|███████▊  | 129/166 [02:53<07:17, 11.81s/it]core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
 80%|████████  | 133/166 [03:51<07:38, 13.90s/it]core        WARNING 	Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.
 81%|████████  | 134/166 [04:04<07:17, 13.66s/it]_api        WARNING 	Failed to align laps for drivers: ['5']
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
 81%|████████▏ | 135/166 [04:16<06:51, 13.28s/it]core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
 83%|████████▎ | 138/166 [05:00<06:34, 14.09s/it]core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
 84%|████████▎ | 139/166 [05:13<06:13, 13.85s/it]core        WARNING 	Driver 63 completed the race distance 00:00.009000 before the recorded end of the session.
 84%|████████▍ | 140/166 [05:26<05:54, 13.64s/it]core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
 86%|████████▌ | 142/166 [05:51<05:18, 13.26s/it]logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!
 86%|████████▌ | 143/166 [06:00<04:29, 11.74s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(882, 2026, 4, 'Sprint')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!

The data you are trying to access has not been loaded yet. See `Session.load`
(884, 2026, 4, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
 86%|████████▌ | 143/166 [06:12<04:29, 11.74s/it]logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!
 87%|████████▋ | 145/166 [06:15<03:26,  9.86s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(887, 2026, 5, 'Sprint')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!
 88%|████████▊ | 146/166 [06:24<03:12,  9.63s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(889, 2026, 5, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!

The data you are trying to access has not been loaded yet. See `Session.load`
(894, 2026, 6, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!

The data you are trying to access has not been loaded yet. See `Session.load`
(899, 2026, 7, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
 88%|████████▊ | 146/166 [06:42<03:12,  9.63s/it]logger      WARNING 	Failed to load race control messages!
 90%|████████▉ | 149/166 [06:42<02:12,  7.82s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(904, 2026, 8, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!
 90%|█████████ | 150/166 [06:48<01:58,  7.38s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(907, 2026, 9, 'Sprint')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!

The data you are trying to access has not been loaded yet. See `Session.load`
(909, 2026, 9, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!

The data you are trying to access has not been loaded yet. See `Session.load`
(914, 2026, 10, 'Race')

 90%|█████████ | 150/166 [07:02<01:58,  7.38s/it]logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!
 92%|█████████▏| 153/166 [07:07<01:30,  6.94s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(919, 2026, 11, 'Race')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
logger      WARNING 	Failed to load weather data!
logger      WARNING 	Failed to load race control messages!
 93%|█████████▎| 154/166 [07:13<01:21,  6.80s/it]

The data you are trying to access has not been loaded yet. See `Session.load`
(922, 2026, 12, 'Sprint')

logger      WARNING 	Failed to load session info data!
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
logger      WARNING 	Failed to load session status data!
logger      WARNING 	Failed to load total lap count!
logger      WARNING 	Failed to load track status data!
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
logger      WARNING 	Failed to load weather data!

any API: 500 calls/h
(924, 2026, 12, 'Race')
any API: 500 calls/h
(929, 2026, 13, 'Race')

 95%|█████████▍| 157/166 [07:22<00:46,  5.14s/it]

any API: 500 calls/h
(934, 2026, 14, 'Race')
any API: 500 calls/h
(939, 2026, 15, 'Race')

 96%|█████████▌| 159/166 [07:23<00:25,  3.71s/it]

any API: 500 calls/h
(942, 2026, 16, 'Sprint')
any API: 500 calls/h
(944, 2026, 16, 'Race')

 97%|█████████▋| 161/166 [07:23<00:13,  2.69s/it]

any API: 500 calls/h
(949, 2026, 17, 'Race')
any API: 500 calls/h
(954, 2026, 18, 'Race')

 98%|█████████▊| 163/166 [07:24<00:05,  1.97s/it]

any API: 500 calls/h
(959, 2026, 19, 'Race')

 99%|█████████▉| 164/166 [07:24<00:03,  1.67s/it]

any API: 500 calls/h
(964, 2026, 20, 'Race')

 99%|█████████▉| 165/166 [07:24<00:01,  1.39s/it]

any API: 500 calls/h
(969, 2026, 21, 'Race')

100%|██████████| 166/166 [07:24<00:00,  2.68s/it]

any API: 500 calls/h
(974, 2026, 22, 'Race')